#!/bin/bash

action=$1
domain=$2
rootDir=$3
version= 1.0
userDir='/var/www/'

if [ "$action" == 'create' ]
	then
		### Add domain in /etc/hosts
		if ! echo "127.0.0.1	$domain" >> /etc/hosts
		then
			echo $"ERROR: Not able to write in /etc/hosts"
			exit;
		else
			echo -e $"Host added to /etc/hosts file \n"
		fi

		if ! echo "
<VirtualHost *:80>
	ServerAdmin admin@gmail.com
	ServerName $domain
	ServerAlias $domain
	DocumentRoot $rootDir
	<Directory />
		AllowOverride All
	</Directory>
	<Directory $rootDir>
		Options Indexes FollowSymLinks MultiViews
		AllowOverride all
		Require all granted
	</Directory>
	ErrorLog /var/log/apache2/$domain-error.log
	LogLevel error
	CustomLog /var/log/apache2/$domain-access.log combined
</VirtualHost>" >> /etc/apache2/extra/httpd-vhosts.conf
			then
				echo -e $"There is an ERROR creating $domain file"
				exit;
			else
				echo -e $"\nNew Virtual Host Created\n"
			fi

else
	newhost=${domain//./\\.}
	sed -i.bank "/$newhost/d" /etc/hosts
	MATCHES="$( grep "<VirtualHost *:80>" /etc/apache2/extra/httpd-vhosts.conf )"
	echo $MATCHES;
fi	